pipeline{
	agent any
	stages{
		stage("stages"){ 
				steps{
					sh ''' 
						echo "checking of poll scm"
				           '''
					sh '''
						df -kh
						du -kH
					   '''
					sh '''
						date
						cal
					   '''
				    }
				
				}	
		}

}

