pipeline {
    agent any 
    stages{
        stage('Timeout'){
            steps {
                retry(3) {
                    sh '''
                    upTIme
                        echo "THIS IS NOT WORING:C"
                       ''' 
                }
            }
        }
    }
}
